name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Week 1 Lab Question 1 Test 3
      id: week-1-lab-question-1-test-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Week 1 Lab Question 1 Test 3
        setup-command: javac MyInfo.java
        command: java MyInfo
        input: John123,Doe,25,New York
        expected-output: Invalid Input
        comparison-method: exact
        timeout: 10
    - name: Week 1 Lab Question 1 Test 2
      id: week-1-lab-question-1-test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Week 1 Lab Question 1 Test 2
        setup-command: javac MyInfo.java
        command: java MyInfo
        input: Mary,Smith,30,Los Angeles
        expected-output: |-
          My Name is Mary Smith.
          I am 30 years old and was born in Los Angeles.
        comparison-method: exact
        timeout: 10
    - name: Week 1 Lab Question 1 Test 4
      id: week-1-lab-question-1-test-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Week 1 Lab Question 1 Test 4
        setup-command: javac MyInfo.java
        command: java MyInfo
        input: Alice,Brown,-5,Chicago
        expected-output: Invalid Input
        comparison-method: exact
        timeout: 10
    - name: Week 1 Lab Question 1 Test 1
      id: week-1-lab-question-1-test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Week 1 Lab Question 1 Test 1
        setup-command: javac MyInfo.java
        command: java MyInfo
        input: Bob,White,22,Miami
        expected-output: |-
          My Name is Bob White.
          I am 22 years old and was born in Miami.
        comparison-method: exact
        timeout: 10
    - name: Week 1 Lab Question 2 Test 1
      id: week-1-lab-question-2-test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Week 1 Lab Question 2 Test 1
        setup-command: javac BirthDay.java
        command: java BirthDay
        input: |-
          6,15,1990
          John,09,20,1985
        expected-output: |-
          In the USA my birthday is: 6/15/1990
          In England my birthday is: 15/6/1990
          In the USA my friend John's birthday is: 9/20/1985
          In England my friend John's birthday is: 20/9/1985
        comparison-method: exact
        timeout: 10
    - name: Week 1 Lab Question 2 Test 2
      id: week-1-lab-question-2-test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Week 1 Lab Question 2 Test 2
        setup-command: javac BirthDay.java
        command: java BirthDay
        input: |-
          3,7,1980
          Tom,6,1,1988
        expected-output: |-
          In the USA my birthday is: 3/7/1980
          In England my birthday is: 7/3/1980
          In the USA my friend Tom's birthday is: 6/1/1988
          In England my friend Tom's birthday is: 1/6/1988
        comparison-method: exact
        timeout: 10
    - name: Week 1 Lab Question 2 Test 3
      id: week-1-lab-question-2-test-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Week 1 Lab Question 2 Test 3
        setup-command: javac BirthDay.java
        command: java BirthDay
        input: |-
          February,15,1990
          John,9,20,1985
        expected-output: Invalid Input
        comparison-method: exact
        timeout: 10
    - name: Week 1 Lab Question 2 Test 4
      id: week-1-lab-question-2-test-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Week 1 Lab Question 2 Test 4
        setup-command: javac BirthDay.java
        command: java BirthDay
        input: |-
          6,0,1990
          John,9,20,1985
        expected-output: Invalid Input
        comparison-method: exact
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        WEEK-1-LAB-QUESTION-1-TEST-3_RESULTS: "${{steps.week-1-lab-question-1-test-3.outputs.result}}"
        WEEK-1-LAB-QUESTION-1-TEST-2_RESULTS: "${{steps.week-1-lab-question-1-test-2.outputs.result}}"
        WEEK-1-LAB-QUESTION-1-TEST-4_RESULTS: "${{steps.week-1-lab-question-1-test-4.outputs.result}}"
        WEEK-1-LAB-QUESTION-1-TEST-1_RESULTS: "${{steps.week-1-lab-question-1-test-1.outputs.result}}"
        WEEK-1-LAB-QUESTION-2-TEST-1_RESULTS: "${{steps.week-1-lab-question-2-test-1.outputs.result}}"
        WEEK-1-LAB-QUESTION-2-TEST-2_RESULTS: "${{steps.week-1-lab-question-2-test-2.outputs.result}}"
        WEEK-1-LAB-QUESTION-2-TEST-3_RESULTS: "${{steps.week-1-lab-question-2-test-3.outputs.result}}"
        WEEK-1-LAB-QUESTION-2-TEST-4_RESULTS: "${{steps.week-1-lab-question-2-test-4.outputs.result}}"
      with:
        runners: week-1-lab-question-1-test-3,week-1-lab-question-1-test-2,week-1-lab-question-1-test-4,week-1-lab-question-1-test-1,week-1-lab-question-2-test-1,week-1-lab-question-2-test-2,week-1-lab-question-2-test-3,week-1-lab-question-2-test-4
