name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Program 1 Test 1
      id: program-1-test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Program 1 Test 1
        setup-command: javac MyInfo.java
        command: java MyInfo
        input: ''
        expected-output: |-
          My Name is Mary Jones.
          I am 21 years old and was born in Cleveland.
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PROGRAM-1-TEST-1_RESULTS: "${{steps.program-1-test-1.outputs.result}}"
      with:
        runners: program-1-test-1
